### ISSUE TITLE
Invalid URL to /migrations/configuration.xsd

### ISSUE THREAD

**Issue by fadoe** [doctrine/migrations-documentation#6]
There is no XML Schema definition at http://doctrine-project.org/schemas/migrations/configuration.xsd how described here: https://github.com/doctrine/migrations-documentation/blob/master/en/reference/introduction.rst#configuration

**Comment by mikeSimonson** [comment]
@Ocramius Does anyone knows were that file is ?
I can't find it in any repo.

**Comment by Ocramius** [comment]
TBH, I'm not sure where this file is /cc @beberlei

**Comment by fadoe** [comment]
It is best to ask the Easter Bunny. :)

**Comment by mikeSimonson** [comment]
@fadoe fixed

**Comment by fadoe** [comment]
@mikeSimonson wow, very fast :laughing:

**Comment by mikeSimonson** [comment]
@fadoe well I had to relearn xsd to be able to recreate it.
